name: lng_adminapp
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  dotted_border: ^2.0.0+2
  flutter_screenutil: ^5.5.3+1
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.3
  http: ^0.13.4
  universal_io: ^2.0.4
  http_interceptor: ^1.0.2
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  expandable: ^5.0.1
  expandable_page_view: ^1.0.14
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  flutter_map: ^0.14.0
  latlong2: ^0.8.1
  cached_network_image: ^3.2.1
  flutter_map_marker_cluster: ^0.4.4
  flutter_bloc: ^8.0.1
  search_choices: ^2.0.20
  table_calendar: ^3.0.5
  image_picker: ^0.8.5+3
  dio: ^4.0.6
  file_picker: ^4.5.1
  image_picker_for_web: ^2.1.8
  http_parser: ^4.0.1
  flutter_dropzone: ^3.0.5
  timelines: ^0.1.0
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^1.0.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
