name: lng_adminapp
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dotted_border: any
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  universal_io: ^2.0.4
  http_interceptor: ^1.0.2
  shared_preferences: ^2.0.8
  intl: ^0.17.0
  expandable: ^5.0.1
  expandable_page_view: ^1.0.9
  json_serializable: ^6.0.1
  json_annotation: ^4.3.0
  flutter_map: ^0.14.0
  latlong2: ^0.8.1
  cached_network_image: ^3.2.0
  flutter_map_marker_cluster: any
  flutter_bloc: ^8.0.0
  search_choices: ^2.0.16
  table_calendar: ^3.0.3
  image_picker: ^0.8.4+4
  dio: ^4.0.4
  file_picker: ^4.3.2
  image_picker_for_web: ^2.1.5
  http_parser: ^4.0.0
  flutter_dropzone: ^3.0.3
  timelines: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^1.0.0
  build_runner: ^2.1.5

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
